"""add problem_meta

Revision ID: be1a84442540
Revises: fd6d9b289c13
Create Date: 2026-08-27 00:24:27.541791
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'be1a84442540'
down_revision = 'fd6d9b289c13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('topics', sa.String(length=512), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'slug', name='uq_problem_meta_platform_slug')
    )
    with op.batch_alter_table('problem_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problem_meta_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_meta_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_meta_slug'))
        batch_op.drop_index(batch_op.f('ix_problem_meta_platform'))

    op.drop_table('problem_meta')
    # ### end Alembic commands ###
