"""initial schema

Revision ID: c75b833c2454
Revises: 
Create Date: 2026-08-04 05:01:54.661596
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c75b833c2454'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=True),
    sa.Column('github_id', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('skill_level', sa.String(length=16), nullable=False),
    sa.Column('tone', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_github_id'), ['github_id'], unique=True)

    op.create_table('card_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_feedback_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_feedback_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('streaks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('longest', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('freezes_left', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('xp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xp_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_events_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_events_user_id'), ['user_id'], unique=False)

    op.create_table('hint_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hint_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hint_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hint_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hint_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hint_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hint_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_hint_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_hint_events_at'))

    op.drop_table('hint_events')
    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_xp_events_slug'))
        batch_op.drop_index(batch_op.f('ix_xp_events_at'))

    op.drop_table('xp_events')
    op.drop_table('streaks')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_slug'))

    op.drop_table('sessions')
    with op.batch_alter_table('card_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_card_feedback_slug'))
        batch_op.drop_index(batch_op.f('ix_card_feedback_at'))

    op.drop_table('card_feedback')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_github_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
