"""add session platform

Revision ID: fd6d9b289c13
Revises: c75b833c2454
Create Date: 2026-08-08 23:15:57.533080
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'fd6d9b289c13'
down_revision = 'c75b833c2454'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Autogenerate produced this as NOT NULL with no default, which fails the
    # moment the table has rows — every existing session would have nothing to
    # put in the new column. A server_default backfills them, and 'leetcode' is
    # correct for all of them because it was the only platform that existed.
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('platform', sa.String(length=32), nullable=False, server_default='leetcode')
        )
        batch_op.create_index(batch_op.f('ix_sessions_platform'), ['platform'], unique=False)

    # Drop the default once the backfill is done: the application always supplies
    # a platform, and leaving it would silently accept rows that forgot to.
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('platform', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_platform'))
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
